[language-server.typos]
command = "typos-lsp"

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "typos"]

[[language]]
name = "markdown"
language-servers = ["typos"]

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
checkOnSave = true

[language-server.rust-analyzer.config.check]
command = "clippy"
allTargets = true
allFeatures = true
extraArgs = ["--", "-D", "warnings"]